- xbatcher/generators.py
- xbatcher/tests/test_generators.py
Used to be called `batch`. Now `sample`.
cc @anirban89
> rename batch dim

- xbatcher/tests/test_generators.py
This was necessary for me to get the tests to pass locally. Not sure what changed.
> fix stack order

- doc/api.rst
- doc/index.rst
- doc/roadmap.rst
cc @rabernat @tomaugspurger @jbednar
> add roadmap to docs

- .github/workflows/main.yaml
- .pre-commit-config.yaml
- conftest.py
- xbatcher/generators.py
- xbatcher/tests/test_generators.py
some minor cleanup and a small fix to a failing test (I'll highlight below).
> fix failing ci

- README.rst
- ci/requirements/doc.yml
> Install pangeo-sphinx-book-theme from conda-forge

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Initial setup of using release-drafter
> initial setup of release-drafter

- .github/release-drafter.yml
Adds a documentation and enhancements section, updates maintenance label
> Add two sections to release drafter

- asv_bench/asv.conf.json
- ci/requirements/asv.yml
Specifying a conda environment for asv to use is required since https://github.com/xarray-contrib/xbatcher/pull/100 removed requirements.txt.
Fixes #
> Add environment file for asv

- pyproject.toml
> Specify minimum Python version in project metadata

- .github/release-drafter.yml
Update format for consistency with final release notes
Fixes #
> Post-release notes drafter update

- xbatcher/generators.py
No substantive changes here, just working towards improving maintainability.
Fixes #
> Use more informative internal variable and function names and keyword-only arguments

- .github/workflows/main.yaml
Avoid running tests twice per push to PRs (e.g., https://github.com/xarray-contrib/xbatcher/pull/140)
Fixes #
> Only run CI on PRs and pushes to main

- xbatcher/generators.py
> Fix type hints for latest version of mypy

- README.rst
- doc/_static/logo.svg
- doc/_static/switcher.json
- doc/api.rst
- doc/conf.py
- doc/contributing.rst
- doc/demo.ipynb
- doc/index.rst
- doc/roadmap.rst
- xbatcher/generators.py
A few documentation improvements
- Adds a (draft) xbatcher logo
- Add a version switcher for the sphinx-pydata-theme
- Fix the demo notebook to account for new handling of overlapping patches #132 
- Fix grammar in a few places
Fixes #
> Add logo, version switcher, and docs corrections

- doc/conf.py
This should fix the ReadTheDocs build error on main.
Fixes #
> Set json_url to GitHub repo

- doc/conf.py
In order to make the path https://xbatcher.readthedocs.io/en/latest/_static/switcher.json valid
Fixes #
> Temporarily disable version switcher

- .pre-commit-config.yaml
- doc/conf.py
Fixes the readthedocs failures
> Remove unsupported sphinx theme option

- .github/dependabot.yml
> group dependabot updates to reduce noise

- .gitignore
- .pre-commit-config.yaml
- asv_bench/benchmarks/accessors.py
- asv_bench/benchmarks/batches.py
- asv_bench/benchmarks/generators.py
- asv_bench/benchmarks/loaders.py
- doc/conf.py
- pyproject.toml
- setup.cfg
- xbatcher/__init__.py
- xbatcher/accessors.py
- xbatcher/generators.py
- xbatcher/loaders/keras.py
- xbatcher/loaders/torch.py
- xbatcher/testing.py
- xbatcher/tests/test_accessors.py
- xbatcher/tests/test_generators.py
- xbatcher/tests/test_keras_loaders.py
- xbatcher/tests/test_print_versions.py
- xbatcher/tests/test_torch_loaders.py
- xbatcher/util/print_versions.py
- replaces black/isort/flake8 with ruff
- removes unnecessary setup.cfg configuration file
> Update pre-commit hooks

- .github/workflows/main.yaml
- .github/workflows/pypi-release.yaml
- ci/requirements/asv.yml
- ci/requirements/doc.yml
- ci/requirements/environment.yml
- pyproject.toml
> test against Python 3.12 and bump python versions used in CI

- .gitignore
- ci/requirements/doc.yml
- doc/caching.ipynb
- doc/contributing.rst
- doc/index.rst
- doc/user-guide/caching.ipynb
- doc/user-guide/index.rst
> Add documentation for caching feature

- CITATION.cff
- README.rst
- doc/_static/switcher.json
> Add zenodo and citation information

- pyproject.toml
- xbatcher/generators.py
> Refactor BatchSchema and BatchGenerator for handling of optional parameters

- readthedocs.yaml
> Update Read the Docs configuration to use Ubuntu 24.04 and latest Mambaforge

- ci/requirements/doc.yml
- doc/user-guide/index.rst
- doc/user-guide/training-a-neural-network-with-keras-and-xbatcher.ipynb
> Add Keras tutorial for training neural networks with Xbatcher to user guide
