xarray-contrib/xbatcher

xbatcher/generators.py

The current assertion breaks if we want to get 1 sample per batch (where the input dims and output dims are identical). Changing < to <= to allow such cases.

allow equal stride and dimsize

---

.github/workflows/main.yaml
.pre-commit-config.yaml
dev-requirements.txt
xbatcher/features.py
xbatcher/tests/test_generators.py

This PR adds a few tests that get xbatcher to 100% test coverage. 
I've also removed the lint check and will active pre-commit.ci in its place.

100% test coverage

---

xbatcher/tests/test_generators.py

This PR verifies that the slices are correct inside `xbatcher/tests/test_generators.py::test_batch_3d_1d_input`.
Closes #65

Test against expected batch in test_batch_3d_2d_input

---

doc/conf.py
xbatcher/generators.py

A few small fixes - 
- configure sphinx copybutton to work with the ipython directive in RST files
- update the dimension name from ``batch`` to ``sample`` in the docstring (follow-up to https://github.com/pangeo-data/xbatcher/pull/1).
- document the name of the level in the sample MultiIndex that corresponds to the batch ID

Fix copybutton and sample dim name in docstring

---

.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
asv_bench/asv.conf.json
asv_bench/benchmarks/__init__.py
asv_bench/benchmarks/benchmarks.py
dev-requirements.txt
doc/contributing.rst
doc/index.rst

This PR adds basic benchmarks using [ASV](https://asv.readthedocs.io/en/stable/), as proposed by @jhamman in #42. The steps for running the benchmarks are documented in a new contributing guide. This PR does not add any CI workflows for running the benchmarks because that could be configured separately and is not needed for the more immediate goal of identifying performance bottlenecks.
As @rabernat noted in https://github.com/pangeo-data/xbatcher/issues/37#issuecomment-970720843, this is only one component of the optimization recipe. While `asv` can report cprofile results, the results are stored in `.json` files which are possible but difficult to extract. Instead, it is generally easier to copy the benchmark and interpret separately using analyzers like …

Setup benchmarks

---

.github/workflows/main.yaml
setup.py

Following https://numpy.org/neps/nep-0029-deprecation_policy.html, drop support for Python 3.7. Update CI to run tests with Python 3.10.

Drop support for Python 3.7

---

xbatcher/accessors.py
xbatcher/generators.py
xbatcher/loaders/keras.py
xbatcher/loaders/torch.py
xbatcher/tests/test_generators.py
xbatcher/tests/test_keras_loaders.py
xbatcher/tests/test_torch_loaders.py

Removes need for using `_as_xarray_dataset` so xr.DataArray inputs are preserved as xr.DataArray objects on the returned output.
Does so by changing [`.dims`](https://docs.xarray.dev/en/v2022.03.0/generated/xarray.Dataset.dims.html) (which returns a different thing between `xr.Dataset` and `xr.DataArray`) to [`.sizes`](https://docs.xarray.dev/en/v2022.03.0/generated/xarray.Dataset.sizes.html) which is a property added in `xarray` v0.9.0 (25 January 2017), see also https://github.com/pydata/xarray/issues/921.
Note that this change is backward incompatible, so an xbatcher v0.2.0 release might be needed. Happy to help out with setting up some of the release infrastructure if needed, e.g. if there's time during the SciPy sprint :smile:
Fixes #70

Use .sizes instead of .dims for xr.Dataset/xr.DataArray compatibility

---

xbatcher/accessors.py
xbatcher/tests/test_accessors.py
xbatcher/tests/test_torch_loaders.py

Convert xarray.Dataset to xarray.DataArray first, so that the `.data` method works to get the underlying array which can be converted to a torch.Tensor. Also added parametrized unit tests, only for the 2D ('x', 'y') case for both `xarray.DataArray` and `xarray.Dataset`.
TODO:
Fixes #84, continuation of #71

Let torch accessor and dataloader handle either xarray.DataArray or xarray.Dataset inputs

---

.github/ISSUE_TEMPLATE/config.yml
CODE_OF_CONDUCT.md
README.rst
asv_bench/asv.conf.json
doc/conf.py
doc/contributing.rst
doc/demo.ipynb
doc/index.rst
setup.py

Even though [GitHub sets up redirects for the transferred repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository), it will be more clear to have the links directly point to the xarray-contrib org. This PR updates all such links except in the demo and code of conduct, which require larger updates.

Update links for GitHub org transfer

---

CODE_OF_CONDUCT.md

Removes CODE_OF_CONDUCT.md, since GitHub will pick up https://github.com/xarray-contrib/.github/blob/main/CODE_OF_CONDUCT.md.
Fixes #

Rely on xarray-contrib code of conduct

---

doc/conf.py

I landed on the `xbatcher` docs and was interested in checking out the source in GitHub. It wasn't difficult to find the GitHub repo, but did require me do a Google search. This PR adds a GitHub icon to the docs that links directly to the project GitHub repo (see the screenshot below)

Add GitHub button to docs

---

setup.cfg
xbatcher/__init__.py
xbatcher/_version.py

PR for Issue #89 
Fixes #89 
cc @maxrjones

issue #89. Use importlib.metadata rather than pkg_resources

---

.github/release-drafter.yml

Updating the configuration because the xbatcher release tag does not have the preceding **v** (e.g., https://github.com/xarray-contrib/xbatcher/tags)
Fixes #

Fix resolved version

---

.pre-commit-config.yaml
asv_bench/benchmarks/benchmarks.py
doc/conf.py
doc/demo.ipynb
setup.py
xbatcher/__init__.py
xbatcher/accessors.py
xbatcher/generators.py
xbatcher/loaders/torch.py
xbatcher/tests/test_accessors.py
xbatcher/tests/test_generators.py
xbatcher/tests/test_keras_loaders.py
xbatcher/tests/test_print_versions.py
xbatcher/tests/test_torch_loaders.py
xbatcher/util/print_versions.py

Simplifies pre-commit and tool configuration, Fixes https://github.com/xarray-contrib/xbatcher/issues/102

Use defaults for Black code formatting

---

xbatcher/accessors.py
xbatcher/tests/test_accessors.py

Adds to: https://github.com/xarray-contrib/xbatcher/issues/83#issue-1340867381. Based off changes in PR: https://github.com/xarray-contrib/xbatcher/pull/85. 
- method `_as_xarray_dataarray` moved outside of `TorchAccessor` class. 
- `_as_xarray_dataarray` method modified to use `is_instance` instead of try:except. 
- unit test added to cover `_as_xarray_dataarray`
- Attempt at `KerasAccessor` and corresponding tests.

TFAccessor and _as_xarray_dataarray update

---

LICENSE

This updates the Xbatcher license file to Apache 2.0. Previously it was MIT but there was some confusing related to the setup.py/pyproject.toml config being listed as Apache.
Fixes #99

change license to Apache 2.0 

---

xbatcher/generators.py

Generating batches in `__init__` is slow and memory intensive, related to  #111  and #109. Initialization is changed to load indices into memory rather than corresponding datasets. The change enabled the initialization a 1.7 TB dataset with 1m+ samples, 30+ spatial features, in about 10 seconds which was previously overloading memory. 
Rather than filling `_batches` with `DataArrays` and `Datasets`, it is filled with indices from `selector = {key: slice for key, slice in zip(dims, slices)}`.  This required an update to the `concat_input_dims` option where the operation is done in `__getitem__()`.  It is possible that this change decreases performance when this `concat_input_dims=True`.

Lazily generate batches

---

doc/index.rst
pyproject.toml
xbatcher/loaders/keras.py
xbatcher/loaders/torch.py

This PR adds information about optional dependencies to the installation instructions and improves the ImportError message when trying to use the data loaders without having PyTorch and/or TensorFlow installed.
Open to opinions about whether these error messages should also be used for the torch and tf xarray accessors and if it's necessary to add tests for this case. This drops code coverage to 99%.
Fixes #

Use informative error message for optional dependency imports

---

ci/requirements/doc.yml
doc/conf.py
doc/demo.ipynb

Automatically execute the demo notebook when building the docs.
Fixes #

Use nbsphinx to execute demo notebook

---

xbatcher/accessors.py
xbatcher/generators.py

Making it easier to catch errors, for example for dataset/dataarray differences.
Fixes #

Add type hints for generators and accessors

---

xbatcher/testing.py
xbatcher/tests/test_generators.py

This PR adds two tests for BatchGenerator when there are one or more dimensions included in both input_dims and batch_dims. The testing utilities are updated to account for this case. The tests currently fail due to https://github.com/xarray-contrib/xbatcher/issues/131, but including them will be helpful for finishing #132.

Add tests for duplicate dims in batch_dims and input_dims

---

xbatcher/__init__.py
xbatcher/accessors.py
xbatcher/generators.py
xbatcher/testing.py
xbatcher/tests/test_generators.py

This PR is a major overhaul of xbatcher’s internals. Users should not notice any external changes, apart from bug fixes and some performance differences.
In v0.2.0, information about the batch_selectors was stored as a dict in the `._batch_selectors` attribute of the `BatchGenerator` class. This PR introduces `BatchSchema` which contains all necessary information about the batch selectors. `BatchGenerator` now creates an instance of  `BatchSchema`, which handles the creation of `selectors` object. The purpose of `BatchGenerator` is to create batches (xarray Datasets/DataArrays) from those selector objects. This opens up possibilities including serializing/deserializing the BatchSchema (e.g., `BatchSchema.to_json()` and `BatchSchema.from_json()`), …

New BatchSchema class to generate patch selectors and combine into batch selectors

---

asv_bench/benchmarks/benchmarks.py

In this PR the benchmarks iterate through the batch generator for a more complete evaluation of performance now that batch generation is lazy. Further improvements could include separate metrics for creating the batch selectors versus indexing on batches, but this is a step forward.
Fixes #

Iterate through batch generator in benchmarks 

---

README.rst
ci/requirements/doc.yml
doc/api.rst
doc/conf.py
doc/contributing.rst
doc/index.rst

Changes theme to pydata-sphinx-theme, adds the BatchSchema to the API documentation and adds a workflow to the contributing guide.
Unfortunately the Jupyter notebook rendering issues for xarray datasets still occurs via read the docs for the furo theme, even though that doesn't happen locally.
Fixes #

Update theme and reference documentation

---

.github/workflows/main.yaml
.github/workflows/pypi-release.yaml
.github/workflows/testpypi-release.yaml
README.rst
pyproject.toml
setup.py

- Upload to TestPyPI on push to main
- Remove setup.py, which is not needed for setuptools>=64.0.0
- Fix readme syntax
- Use `local_scheme = "node-and-date"`
Fixes #

Update packaging configuration and workflow

---

.github/workflows/testpypi-release.yaml
doc/conf.py
xbatcher/loaders/torch.py

Enable version switcher

---

.github/workflows/main.yaml
.github/workflows/pypi-release.yaml
.pre-commit-config.yaml
ci/requirements/doc.yml
pyproject.toml
xbatcher/generators.py
xbatcher/tests/test_keras_loaders.py
xbatcher/tests/test_torch_loaders.py

Drop Python 3.8 since it's no longer supported by Xarray (https://github.com/pydata/xarray/pull/7461)
Fixes #

Drop Python 3.8

---

ci/requirements/doc.yml
doc/conf.py
doc/index.rst
doc/tutorials-and-presentations.rst

Add a link to the AMS recording and slides.
Closes https://github.com/xarray-contrib/xbatcher/issues/91

Add tutorials and presentations section

---

.github/workflows/main.yaml
pyproject.toml
xbatcher/accessors.py
xbatcher/generators.py
xbatcher/loaders/keras.py
xbatcher/loaders/torch.py
xbatcher/testing.py

- Now that xarray has officially dropped supprt for Python 3.9: https://github.com/pydata/xarray/pull/8937, this PR bumps the required/minimum Python version to 3.10
- Closes #230

Drop support for Python 3.9

---

.pre-commit-config.yaml
doc/demo.ipynb

Update pre-commit hooks to use latest versions of ruff and mypy

---

.pre-commit-config.yaml
xbatcher/loaders/torch.py
xbatcher/tests/test_torch_loaders.py

This PR introduces a number of changes to xbatcher's pytorch `MapDataset` class. These changes came out of the learnings while preparing [my AMS talk](https://ams.confex.com/ams/104ANNUAL/meetingapp.cgi/Paper/440043) (slides and blog post coming soon). The changes here allow for more control over how w
- includes concurrent loading of x/y batches with dask.compute()
- transforms now are expected to take an xarray object and return a torch.Tensor

Refactor Pytorch dataset 
